"use client";

interface DashboardFooterProps {
  verifiedAt: string;
}

function formatVerifiedAt(value: string): string {
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return value;
  }

  return new Intl.DateTimeFormat("en-IN", {
    timeZone: "Asia/Kolkata",
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  }).format(parsed);
}

export default function DashboardFooter({
  verifiedAt,
}: DashboardFooterProps) {
  return (
    <footer className="mt-10 border-t border-slate-200 pt-4 text-center text-xs text-slate-400">
      <p>Verified on {formatVerifiedAt(verifiedAt)}</p>
      <p className="mt-1">Generated by LeXTrace</p>
      <p className="mt-1">Human-verified trusted view</p>
    </footer>
  );
}
